import { redirect } from 'next/navigation';
import { canBootstrapOwner } from '@capsicum/application';
import { ErrorNotice } from '../../components/page-primitives';
import { getDatabasePool } from '../../lib/database';
import { getOptionalPrincipal } from '../../lib/session';
import { queryError } from '../../lib/presentation';
import { bootstrapOwnerAction } from '../actions';

export const dynamic = 'force-dynamic';

export default async function OnboardingPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  if (await getOptionalPrincipal()) redirect('/');
  const bootstrapConfigured = /^[a-f0-9]{64}$/i.test(process.env.BOOTSTRAP_TOKEN_SHA256 ?? '');
  let allowed = false;
  try { allowed = await canBootstrapOwner(getDatabasePool()); } catch { /* rendered below */ }
  if (!allowed && process.env.DATABASE_URL) redirect('/sign-in');
  const query = await searchParams;
  return (
    <section className="auth-card wide">
      <span className="eyebrow">One-time secure bootstrap</span>
      <h1>Create the first workspace</h1>
      <p className="lede">This creates the first owner and workspace exactly once. You must also provide the independent installation token generated by the person who deployed the system.</p>
      <ErrorNotice message={queryError(query.error) ?? (!process.env.DATABASE_URL ? 'DATABASE_URL is required before onboarding.' : !bootstrapConfigured ? 'BOOTSTRAP_TOKEN_SHA256 is not configured. The installer must generate a high-entropy token, store only its SHA-256 digest in the deployment environment, and give the original token to the intended owner through a separate secure channel.' : null)} />
      <form action={bootstrapOwnerAction} className="form-grid">
        <div className="field full"><label htmlFor="installationToken">Installation token</label><input id="installationToken" name="installationToken" type="password" minLength={32} maxLength={512} autoComplete="one-time-code" spellCheck={false} required /><small>This is not your password. It is a single-use deployment credential and stops working as soon as the first owner is created.</small></div>
        <div className="field"><label htmlFor="displayName">Your name</label><input id="displayName" name="displayName" autoComplete="name" required /></div>
        <div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" autoComplete="email" required /></div>
        <div className="field"><label htmlFor="workspaceName">Workspace name</label><input id="workspaceName" name="workspaceName" required /></div>
        <div className="field"><label htmlFor="workspaceSlug">Workspace web name</label><input id="workspaceSlug" name="workspaceSlug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="my-pepper-project" required /><small>Lowercase letters, numbers, and hyphens only. This is a stable system identifier, not the display name.</small></div>
        <div className="field full"><label htmlFor="password">Owner password</label><input id="password" name="password" type="password" minLength={12} autoComplete="new-password" required /><small>Use 12–256 characters and at least three of: lowercase, uppercase, numbers, or symbols. Avoid common passwords and the word “capsicum.” Store it in a password manager.</small></div>
        <div className="full"><button className="button" type="submit" disabled={!process.env.DATABASE_URL || !bootstrapConfigured}>Create governed workspace</button></div>
      </form>
    </section>
  );
}
